[project]
name = "pdf-qa-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.11.0",
    "fastapi>=0.142.2",
    "pinecone>=10.0.0",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]
